### ISSUE TITLE
Deploy bot in Raspberry Pi

### ISSUE THREAD

**Issue by jesusjimsa** [jesusjimsa/COVID-19-Data-Twitter-Spain#48]
The end of the free trial of AWS is near, and a Raspberry Pi should be more than enough for this bot to continue working. In fact, it's probably enough for the booster code that couldn't be deployed in AWS.

## Tasks

- [ ] Clone repository in Raspberry Pi
- [ ] Copy Twitter credentials into Raspberry Pi
- [ ] Set up cron job to run at the same time it's running already in AWS
- [ ] Set up booster vaccine code

**Comment by jesusjimsa** [comment]
The bot is now stopped, no need to move it to the Raspberry Pi.
